# This file is machine-generated - editing it directly is not advised

[[BinaryProvider]]
deps = ["Libdl", "SHA"]
git-tree-sha1 = "29995a7b317bbd06be147e1974a3541ce2502dca"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.7"

[[CxxWrap]]
deps = ["BinaryProvider", "Libdl"]
git-tree-sha1 = "20dc870e3c8a52969bd30992d87bd57e0952b2ba"
pinned = true
repo-rev = "0c82e3e"
repo-url = "https://github.com/JuliaInterop/CxxWrap.jl.git"
uuid = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
version = "0.9.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
