name: CI
on:
  push:
    paths:
      - .github/workflows/ci.yml
      - Project.toml
      - "**.jl"
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - Project.toml
      - "**.jl"
jobs:
  test:
    name: Julia ${{ matrix.julia_version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia_version:
          - 1.3
          - 1.4
          - 1.5
          - 1.6
          - nightly
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    if: |
      !contains(format('{0} {1} {2}',
                github.event.head_commit.message,
                github.event.pull_request.title,
                github.event.pull_request.body), '[skip ci]')
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia_version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia+${{ matrix.julia_version }}-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia+${{ matrix.julia_version }}-${{ env.cache-name }}-
            ${{ runner.os }}-julia+${{ matrix.julia_version }}-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
