name: CI
on:
  push:
    paths:
      - .github/workflows/ci.yml
      - Project.toml
      - "**.jl"
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - Project.toml
      - "**.jl"
jobs:
  check_skip:
    name: Check if should skip CI
    runs-on: ubuntu-latest
    if: |
      !contains(format('{0} {1} {2}',
                github.event.head_commit.message,
                github.event.pull_request.title,
                github.event.pull_request.body), '[skip ci]')
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    needs: check_skip
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - 1.3
          - 1.4
          - 1.5
          - nightly
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-${{ matrix.version }}-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.version }}-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.version }}-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
