name: TagBot
on:
  schedule:
    - cron: 0 * * * *
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          user: Rui Ventura
          email: rventura.pt@outlook.com
          gpg: ${{ secrets.GPG_KEY }}
          gpg_password: ${{ secrets.GPG_PASSWORD }}
          ssh: ${{ secrets.SSH_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
